### ISSUE TITLE
t_id vom System generieren lassen

### ISSUE THREAD

**Issue by schmandr** [sogis/migration-sogis-db#10]
Die t_id soll vom System generiert werden. Der Standardwert für dieses Attribut ist ja jeweils definiert als `nextval('schemaname.t_ili2db_seq')`. Wenn du also die folgende Zeile weglässt, wird die t_id automatisch vergeben.

https://github.com/sogis/migration-sogis-db/blob/7fbe0b5dd7c4e48668f87c93a49212901d8eeaf0/gretljobs/afu_geologie/abrisskanten.sql#L2

Das gilt dann auch für die anderen SQL-Dateien.

**Comment by barpasen** [comment]
Ich werde das in meine Checkliste schreiben, dass ich die Zeile jeweils am Ende der rausnehme, aber für die Kontrolle der Daten ist der Wert der "ogc_fid" oder eine andere ID nützlich.
