### ISSUE TITLE
Wie stellen wir sicher, dass bei der Migration diese Objekte nicht vergessen gehen?

### ISSUE THREAD

**Issue by schmandr** [sogis/migration-sogis-db#11]
https://github.com/sogis/migration-sogis-db/blob/7fbe0b5dd7c4e48668f87c93a49212901d8eeaf0/gretljobs/afu_geologie/grundschicht.sql#L178-L180

https://github.com/sogis/migration-sogis-db/blob/7fbe0b5dd7c4e48668f87c93a49212901d8eeaf0/gretljobs/afu_geologie/schichtfallen.sql#L20

**Comment by barpasen** [comment]
Die sind nur noch solange drin, bis ich das selber abgeklärt oder mit Markus Stähli besprochen habe. Werde ich auch in meine Checkliste aufnehmen, dass ich solche Ausnahmen am Ende herausnehme.
