### ISSUE TITLE
Einheiten im Kommentar angeben?

### ISSUE THREAD

**Issue by schmandr** [sogis/migration-sogis-db#13]
Wäre es evtl. sinnvoll, die Einheiten (Quadratmeter, Hektaren, ?) im Kommentar anzugeben?
https://github.com/sogis/migration-sogis-db/blob/ffc085a7df338b8e9a0c07f450297fce179a374b/models/SO_AFU_Baugrundklassen_pub_20201023.ili#L37

Dasselbe gälte dann auch hier: https://github.com/sogis/migration-sogis-db/blob/ffc085a7df338b8e9a0c07f450297fce179a374b/models/SO_AFU_Baugrundklassen_pub_20201023.ili#L40

**Comment by schmandr** [comment]
Bei unserem MOpublic-Modell kommt die Variante mit den Units wie auch die Variante mit "Angabe im Kommentar" vor: http://geo.so.ch/models/AGI/SO_AGI_MOpublic_20190424.ili

**Comment by barpasen** [comment]
Ich habe die Einheiten im Kommentar ergänzt. Ein Test mit Units aus <Units-20050616.ili>lieferte einen Fehler beim Ausführen von ili2pg. Im Handbuch "Modellbasierte Datenerfassung" steht nichts zu diesen Einheiten (z.Bsp. m2).

**Comment by barpasen** [comment]
Nun habe ich gerade gesehen, dass die Bezeichnung der Klassen aktuell in der Pub-DB nicht mit den Einträgen in der MetaDB übereinstimmen. Muss ich nochmal anschauen.

**Comment by claeis** [comment]
Wenn ili2db beim Modell Units ein Fehler liefert, bitte bei ili2db ein Issue machen.

Einheiten mit den von der Sprache INTERLIS vorgesehenen Möglichkeiten anzugeben, finde ich besser (als im Kommentar).

```
INTERLIS 2.3;
MODEL ModelA 
   AT "mailto:user@localhost"
   VERSION "20061021" =
  IMPORTS Units;
  DOMAIN
    Winkel = 0..399 [Units.Gon];

END ModelA.
```

**Comment by barpasen** [comment]
Hoi Claude, danke für den Tipp, wusste gar nicht, dass da noch jemand reinschaut :-)
Nachdem ich die Units korrekt ins Modell importiert hatte, klappte das mit ili2pg einwandfrei.
