### ISSUE TITLE
Kommentar bei Attribut "Zuordnung" fehlt

### ISSUE THREAD

**Issue by schmandr** [sogis/migration-sogis-db#14]
Bei https://github.com/sogis/migration-sogis-db/blob/f494fe6210387fa592a05e5c6407190c9b06752e/models/SO_AFU_Baugrundklassen_pub_20201023.ili#L44 und beim nächsten Attribut ist der Kommentar "Vgl. Zuordnung". Aber beim Attribut "Zuordnung" fehlt dann der Kommentar. Und ich komme ich nicht draus, wie denn diese beiden Kommentare zu verstehen sind.

**Comment by schmandr** [comment]
Dasselbe gilt fürs Erfassungsmodell.

**Comment by barpasen** [comment]
Beschreibung bei Zuordnung fehlte, sehr verständlich ist das immer noch nicht, aber mehr gibt die MetaDB nicht her.

**Comment by barpasen** [comment]
Nach Besprechung und Kontrolle geschlossen
