### ISSUE TITLE
Besser "unbekannt" stehen lassen statt "-"?

### ISSUE THREAD

**Issue by schmandr** [sogis/migration-sogis-db#3]
https://github.com/sogis/migration-sogis-db/blob/7fbe0b5dd7c4e48668f87c93a49212901d8eeaf0/models/SO_AFU_Geologie_20200831.ili#L426
https://github.com/sogis/migration-sogis-db/blob/7fbe0b5dd7c4e48668f87c93a49212901d8eeaf0/models/SO_AFU_Geologie_20200831.ili#L449
https://github.com/sogis/migration-sogis-db/blob/7fbe0b5dd7c4e48668f87c93a49212901d8eeaf0/models/SO_AFU_Geologie_20200831.ili#L522

**Comment by barpasen** [comment]
Da ich die Attributwerte möglichst gleich wie in der aktuellen Pub-DB (afu_geologie) halten möchte, habe ich diese Einträge so belassen.

**Comment by schmandr** [comment]
Beschluss: Den Strich beim dispName stehen lassen. Denn wir wissen eigentlich nicht exakt, was mit dem Strich gemeint ist, nehmen aber an, dass er "unbekannt" bedeutet. Dadurch, dass wir den Strich noch als dispName stehen lassen, bleibt ersichtlich, dass es ursprünglich so im Attribut stand.
