### ISSUE TITLE
Hier und auf den folgenden paar Zeilen steht der "ili2db.dispName" jeweils zweimal

### ISSUE THREAD

**Issue by schmandr** [sogis/migration-sogis-db#4]
https://github.com/sogis/migration-sogis-db/blob/7fbe0b5dd7c4e48668f87c93a49212901d8eeaf0/models/SO_AFU_Geologie_20200831.ili#L494-L495

**Comment by barpasen** [comment]
Das könnte vom Wechsel des UML-Editors stammen, im aktuellen (kolumbianischen von Stefan) habe ich keine doppelten Einträge gefunden, nachdem ich jeweils bei einem Element den Eintrag in "Element Display Name" gelöscht und dann denselben Text wieder geschrieben habe  (copy/paste), waren anschliessend alle doppelten Einträge bei dieser Domain weg!!!
