### ISSUE TITLE
Attribut "Schichtgliederung" hat keinen Kommentar

### ISSUE THREAD

**Issue by schmandr** [sogis/migration-sogis-db#6]
Folgendes Attribut hat keinen Kommentar. Aber vielleicht braucht es hier auch keinen.
https://github.com/sogis/migration-sogis-db/blob/7fbe0b5dd7c4e48668f87c93a49212901d8eeaf0/models/SO_AFU_Geologie_20200831.ili#L610

**Comment by barpasen** [comment]
Ergänzt mit Geologische Schichtgliederung (von... bis...)
