### ISSUE TITLE
Leerschlag vor "89" weglassen; und "vertikal" statt "geneigt"

### ISSUE THREAD

**Issue by schmandr** [sogis/migration-sogis-db#8]
https://github.com/sogis/migration-sogis-db/blob/7fbe0b5dd7c4e48668f87c93a49212901d8eeaf0/models/SO_AFU_Geologie_20200831.ili#L712

Der Kommentar müsste wahrscheinlich so lauten:
`vertikal - Schichtneigung 1-89°`

Oder sogar
`vertikal - Schichtneigung 90°`?

**Comment by barpasen** [comment]
geneigt - Schichtneigung 1-89° ist korrekt.
